Avoid duplicate title errors with complete titles
sourcegraph/about pull request #1562
Opened 2020-09-12 00:08 UTC by aileenrose

Updated titles on onboarding and goals pages.

2020-09-12 00:08 UTC, uwedeportivo approved these changes

2020-09-14 15:45 UTC, nicksnyder requested changes
What problem does this solve?

Pages should be able to choose whatever titles they choose, duplication shouldn't be a problem.

2020-09-14 16:42 UTC, aileenrose commented
> What problem does this solve?
> 
> Pages should be able to choose whatever titles they choose, duplication shouldn't be a problem.

Even though these pages are directed to a new staff, as a best practice, pages should have unique titles for SEO.   SEO tools like Google Search Console will flag.   Also, great to show consistent titles in search results.

![Screen Shot 2020-09-14 at 9 31 55 AM](https://user-images.githubusercontent.com/2164916/93113218-c37f7600-f66d-11ea-898a-1461895c038f.png)

2020-09-14 22:07 UTC, nicksnyder approved these changes

2020-09-15 00:32 UTC, merged