Fix reference to server vs. .com
sourcegraph/about pull request #2175
Opened 2020-12-14 16:20 UTC by rrhyne

2020-12-14 19:58 UTC, christinaforney requested changes
Added some additional corrections.

2020-12-14 19:58 UTC, christinaforney commented on handbook/communication/content_guidelines/style_and_mechanics.md
> +- **Sourcegraph.com**: The public instance of Sourcegraph for open source code at [sourcegraph.com](https://sourcegraph.com).
```suggestion
- **Sourcegraph Cloud**: The public instance of Sourcegraph for open source code at [sourcegraph.com](https://sourcegraph.com).
```

2020-12-14 19:58 UTC, christinaforney commented on handbook/communication/content_guidelines/style_and_mechanics.md
>  - **Self-hosted Sourcegraph instance**: Only if clarification between Sourcegraph Cloud, managed instances, and on-premises instances is required.
```suggestion
- **Self-hosted Sourcegraph instance or Sourcegraph Server**: The self-hosted Sourcegraph instance maintained by customers. Only if clarification between Sourcegraph Cloud, managed instances, and on-premises instances is required.
```

2020-12-14 19:58 UTC, christinaforney commented on handbook/communication/content_guidelines/style_and_mechanics.md
> +- **Sourcegraph Server**: Only if clarification between the Sourcegraph Cloud instance, self-hosted instances, and managed instances is required.
```suggestion
- **Managed Sourcegraph instance**: A fully isolated Sourcegraph Server deployment maintained by the Sourcegraph team for a customer. Only use if clarification between the Sourcegraph Cloud instance, self-hosted instances, and managed instances is required.
```

2020-12-14 20:23 UTC, rrhyne commented
Ah, I missed all that. Thanks.

2020-12-15 15:45 UTC, christinaforney approved these changes

2020-12-15 20:51 UTC, merged