Create Fedor Korotkov podcast post
sourcegraph/about pull request #5200
Opened 2022-03-11 16:21 UTC by nickmyyz

BZ and YT links TK

Note from Ritza: "We were unsure about the phrase "obstruction battery's" - we've changed it to "abstraction battery's", please double check? We took a particularly relaxed approach to filler words such as "like" in this episode. Let us know if you'd like us to be more heavy handed in future."

2022-03-15 14:34 UTC, csbailey5t requested changes
A few changes or things to check, but this is great!

2022-03-15 14:34 UTC, csbailey5t commented on podcast/2.19.md
> +Yeah, sure. I have a really good blog post about it. I think maybe we can include it in the show notes to the podcast.
We should make sure the blog post mentioned is in the show notes

2022-03-15 14:34 UTC, csbailey5t commented on podcast/2.19.md
> +And there is no work from our side. We just utilize Kubernetes. And, in our case, we utilize GKE— Google's Kubernetes, but Cirrus also supports AWS, CKS, Amazon Kubernetes, and even Oracle Cloud Kube
```suggestion
And there is no work from our side. We just utilize Kubernetes. And, in our case, we utilize GKE— Google's Kubernetes, but Cirrus also supports AWS, CKS, Amazon Kubernetes, and even Oracle Cloud Kubernetes. So you can connect your own infrastructure and run your CI, on your own cluster within your own infrastructure, which is also super beneficial. You can get all the discounts you have from the cloud provider. You have more control over configurations, like some like edge cases and so on.
```

2022-03-15 14:34 UTC, csbailey5t commented on podcast/2.19.md
> +In the very beginning, if you name the dash, you will see this… it's like “Azure blah, blah, blah, kernel.” So it's like the Azure pipeline.
I'm not familiar with the phrase "name the dash" - are we sure of that one?

2022-03-15 14:34 UTC, csbailey5t commented on podcast/2.19.md
> +And, yeah, it's coming in the next few days. There will be a blog post we can probably also include. And we implemented it as an open-source Go package. So basically this package will allow anyone to
Check for this blog post.

2022-03-15 14:34 UTC, csbailey5t commented on podcast/2.19.md
> +Cool. Would it be safe to say that the two biggest benefits of Cirrus is … there's kind of two, and they're separate, at least in my mind. One is just developer experience, the fact that all this is
```suggestion
Cool. Would it be safe to say that the two biggest benefits of Cirrus are … there's kind of two, and they're separate, at least in my mind. One is just developer experience, the fact that all this is configured by hitting cloud APIs. And you don't have to manage a bunch of infrastructure, in order to stand up CI and scale it as your team grows. So developer experience, one.
```

2022-03-15 14:34 UTC, csbailey5t commented on podcast/2.19.md
> +In theory, it shouldn't fail because it's all containerized and blah, blah, blah. But if you're changing out the underlying thing, at the end of the day, it's the abstraction battery's not perfect. R
I think this is "abstraction boundary" but the second word is a bit unclear.

2022-03-15 14:34 UTC, csbailey5t commented on podcast/2.19.md
> +But then there is, of course, problems when you don't have, for example, FreeBSD access, or you don't have macro AST. And your tests are only failing on one particular virtual machine, for example. T
```suggestion
But then there is, of course, problems when you don't have, for example, FreeBSD access, or you don't have macOS. And your tests are only failing on one particular virtual machine, for example. Then it's more convenient to just rerun things in the browser you have. With the terminal access in the browser, you can figure things out and then fix it.
```

2022-03-21 20:49 UTC, jennybergen commented on podcast/2.19.md
> +title: 'Creating one CI to rule them all, with Fedor Korotkov, founder and CTO of Cirrus Labs'
@nickmyyz @csbailey5t Cirrus Labs should be one word: CirrusLabs

2022-03-21 20:50 UTC, jennybergen commented on podcast/2.19.md
> +Why can’t one CI scale alongside a company–from startup to enterprise? In this episode, Fedor Korotkov, founder and CTO of Cirrus Labs, joins Beyang Liu, co-founder and CTO of Sourcegraph, to talk ab
@nickmyyz  @csbailey5t same comment here. The name should be "CirrusLabs," one word. I think the other mentions are all just "Cirrus" in the transcript, so the rest should be okay.

2022-03-21 20:59 UTC, jennybergen commented on podcast/2.19.md
> +
@nickmyyz @csbailey5t I noticed we did not include the "This transcript has been lightly edited for clarity and readability." sentence at the end. Can you please add this?

2022-03-22 14:17 UTC, csbailey5t approved these changes

2022-03-22 14:17 UTC, merged