Workshops page
sourcegraph/about pull request #5563
Opened 2022-07-07 20:50 UTC by bretthayes

Closes #5562 creating a workshops page for workshop sign ups.

### Test

1. Ensure prettier has standardized the proposed changes.
2. Ensure the form captures the data in HubSpot and you receive an email from the HubSpot workflow

2022-07-11 22:59 UTC, st0nebraker requested changes
It looks good to me! But I'm not seeing a HubSpot follow up email after form submission, are you @vanesa ? Just want to confirm the whole workflow is working. Do we need to do more steps on the HubSpot side of things?

2022-07-11 22:59 UTC, st0nebraker commented on src/pages/workshops/coreboot-july-2022.tsx
> +            description: '',
If the description value is blank we can omit the whole line, it's not needed :)

2022-07-11 23:45 UTC, vanesa submitted a review, later dismissed

2022-07-11 23:55 UTC, st0nebraker approved these changes

2022-07-18 15:41 UTC, bretthayes commented on src/pages/workshops/coreboot-july-2022.tsx
> +                        <li> Code Insights</li>
Trim spacing:

```suggestion
                    <p>You'll learn:</p>
                    <ul>
                        <li>How to get access to Sourcegraph</li>
                        <li>Different search types</li>
                        <li>How to solve codebase challenges</li>
                        <li>How to use code intelligence to navigate code efficiently</li>
                        <li>How to do large-scale changes</li>
                        <li>Documenting on Notebooks</li>
                        <li>Code Insights</li>
```

2022-07-25 14:49 UTC, bretthayes commented
This is no longer needed. ([ref](https://sourcegraph.slack.com/archives/C023BV511TR/p1658511086831289?thread_ts=1658509475.151139&cid=C023BV511TR))

2022-07-25 14:49 UTC, closed without merging