Campaign landing page/ Shift Left
sourcegraph/about pull request #5652
Opened 2022-08-04 20:59 UTC by st0nebraker

Adds new landing page for the Shift Left campaign

### Changelog
""

### Note
This will be included in the Resources page

### Test
1. Ensure prettier has standardized the proposed changes.
2. Nav to `/shift-left-the-good-parts` and ensure spec matches on all screen sizes

2022-08-05 16:04 UTC, bretthayes requested changes

2022-08-05 16:04 UTC, bretthayes commented on src/pages/shift-left-the-good-parts.tsx
> +        <ContentSection color="white" className="container max-w-900 py-7 px-0">
The Figma doesn't show this having a smaller width constraint so I don't think we should add the max width. Was this a request?
```suggestion
        <ContentSection color="white" className="container py-7 px-0">
```

2022-08-05 16:04 UTC, bretthayes commented on src/pages/shift-left-the-good-parts.tsx
> +                <h2 className="mb-5 font-weight-bold">Related resources</h2>
Title in the Figma shows differently:
```suggestion
                <h2 className="mb-5 font-weight-bold">Read more about dev tools that accelerate the dev cycle</h2>
```

2022-08-05 16:57 UTC, st0nebraker commented on src/pages/shift-left-the-good-parts.tsx
> +                        host="self"
Ah! Good catch, it was rendering in development and something must've changed before I opened the PR. Got it going now 😎

2022-08-05 17:43 UTC, bretthayes commented
Just something I noticed, but I think maybe we should add some top margin spacing to the caption under in the Video component @st0nebraker

2022-08-05 18:04 UTC, st0nebraker commented
> Just something I noticed, but I think maybe we should add some top margin spacing to the caption in the Video component @st0nebraker

I think so too, especially with the video's getting a box shadow. I added a bit here, what do you think? @bretthayes 
![image](https://user-images.githubusercontent.com/59381432/183134917-43106439-9dff-44fc-8d5c-b9924689a26a.png)

2022-08-05 18:05 UTC, st0nebraker commented
Also, what do you think about this pages slug? I think it should maybe have another content hierarchy folder, like `/campaign/` or something. It'll be included in the Resources page later, so I'm guessing we'll be using the content type: `campaign` or something similar. @bretthayes

2022-08-05 20:21 UTC, bretthayes commented
> > Just something I noticed, but I think maybe we should add some top margin spacing to the caption in the Video component @st0nebraker
> 
> I think so too, especially with the video's getting a box shadow. I added a bit here, what do you think? @bretthayes ![image](https://user-images.githubusercontent.com/59381432/183134917-43106439-9dff-44fc-8d5c-b9924689a26a.png)

That looks nice, and doesn't get hidden in the shadow. Thanks @st0nebraker!

2022-08-05 20:32 UTC, bretthayes commented
> Also, what do you think about this pages slug? I think it should maybe have another content hierarchy folder, like `/campaign/` or something. It'll be included in the Resources page later, so I'm guessing we'll be using the content type: `campaign` or something similar. @bretthayes

I think this page falls under the same bucket as other pages that live under the root that are campaigned as well but it's not exposed to the user that it's a campaign via the URL structure. But maybe another name other than `campaign` would be a good idea for organizing these types of pages under a content type for the resources page. It would also help organize the file tree, so good idea! @st0nebraker

2022-08-05 22:08 UTC, bretthayes submitted a review, later dismissed
This looks good to go! 🚀

2022-08-09 23:09 UTC, st0nebraker commented
Small spacing & title change from stakeholder review. This is ready to ship! Just needs a ✅  @bretthayes

2022-08-10 14:59 UTC, bretthayes approved these changes

2022-08-10 14:59 UTC, merged