Rm Bootstrap > Custom Tooltip & Accordion
sourcegraph/about pull request #5824
Opened 2022-10-05 19:21 UTC by st0nebraker

Closes #5746

### Changelog

### Test
1. Ensure prettier has standardized the proposed changes.

2022-10-07 21:10 UTC, st0nebraker commented on src/components/Tooltip.tsx
> +                    </div>
I just need to write some logic to take care of the overflow offscreen issue here. Since the position can be dynamic, I'm not sure if it should be taken care of here or by what's passed in one level higher by the parent component.
![image](https://user-images.githubusercontent.com/59381432/194652574-335d755a-fb16-4605-8b35-3e0f0f016f06.png)

2022-10-11 15:45 UTC, bretthayes requested changes
This is a great step forward! Nice work Becca! Some suggestions below:

2022-10-11 20:34 UTC, st0nebraker commented on src/components/Tooltip.tsx
> +                    </div>
The tooltip to be relative to it's icon though, so it needs to know where the parent is 🤔 I'm not sure how well that can work with Portal. Or am I missing something? Where would you put a relative positioning for this using Portal?

2022-10-12 16:46 UTC, bretthayes commented on src/components/Tooltip.tsx
> +                    </div>
You could render the tooltip popover itself within the portal which would solve the z-index issues, and then use a ref on the icon, so that when you hover, you can listen for a mouse move event and find the pageX and pageY coordinates to position the popover accordingly. There's some clever examples floating around on Stack Overflow for viewport edge detection 🤓 @st0nebraker

2022-12-20 23:41 UTC, closed without merging