blogpost: migrating from monaco to codemirror
sourcegraph/about pull request #5883
Opened 2022-10-26 09:20 UTC by sixhobbits

### Changelog

### Test

1. Ensure prettier has standardized the proposed changes.

2022-10-26 16:41 UTC, jdorfman commented on content/blogposts/2022/migrating-monaco-codemirror.md
> +published: false
@sixhobbits change `false` to `true`

2022-10-26 19:01 UTC, jdorfman requested changes

2022-10-27 07:46 UTC, sixhobbits commented on content/blogposts/2022/migrating-monaco-codemirror.md
> +published: false
done

2022-10-27 07:46 UTC, sixhobbits commented on content/blogposts/2022/migrating-monaco-codemirror.md
> +![XKCD 2347 showing a structure of blocks with a single small block holing everything up](https://storage.googleapis.com/sourcegraph-assets/blog/codemirror-vs-monaco/image3.png)
done

2022-10-27 16:13 UTC, merged