[SGM-6055] : Cody page
sourcegraph/about pull request #6076
Opened 2023-03-14 07:23 UTC by gitstart-sourcegraph

## Description
Implementation of the Cody landing page from the [design mockup](https://www.figma.com/file/oQgh5R0iSBG3UII6C8CPJ8/Cody-landing-page?node-id=20%3A1357&t=6q10YRBitZeMIgbD-0)

## Ref
[Sourcegraph issue](https://github.com/sourcegraph/about/issues/6055)
GitStart Ticket: [SGM-6055](https://developers.gitstart.com/client/sourcegraph/ticket/SGM-6055)

## Demo video
https://user-images.githubusercontent.com/51731962/224924894-79f57e8b-7283-4c50-98e5-3276e4417de0.mov

2023-03-20 18:48 UTC, sqs requested changes

2023-03-20 18:48 UTC, sqs commented on src/pages/cody.tsx
> +                    Cody is now in Private Beta
```suggestion
                    Cody is now in private beta
```

2023-03-20 18:48 UTC, sqs commented on src/pages/cody.tsx
> +                    results. Cody is now in Private Beta for select users.
```suggestion
                    results.
```

2023-03-20 18:48 UTC, sqs commented on src/pages/cody.tsx
> +                    Request Private Beta access
```suggestion
                    Join private beta waitlist
```

2023-03-20 18:48 UTC, sqs commented on src/pages/cody.tsx
> +            title="Try the Sourcegraph app on your code"
What is the reason for having this CTA here? I'm afraid it will confuse users.

2023-03-22 17:55 UTC, iskyOS approved these changes

2023-03-22 18:00 UTC, merged