Add blog for cody v0.18 for vscode
sourcegraph/about pull request #6618
Opened 2023-12-05 18:39 UTC by jdorfman

2023-12-05 18:54 UTC, kalanchan requested changes

2023-12-05 18:54 UTC, kalanchan commented on content/blogposts/2023/cody-vscode-0-18-release.md
> +The Cody for VS Code v0.18.0 update introduces a new chat interface, allowing for side-by-side chat windows and improved context control, including a reworked context dropdown that shows file names a
```suggestion
The Cody for VS Code v0.18.0 update introduces a new chat interface, allowing for side-by-side chat windows, a reworked context dropdown that shows file names and line ranges, and improved context control using the new Enhanced Context Selector.
```

2023-12-05 18:54 UTC, kalanchan commented on content/blogposts/2023/cody-vscode-0-18-release.md
> +  src="https://storage.googleapis.com/sourcegraph-assets/blog/blog-vscode-v018-release/blog-v018-mention-003.png"
I think this image was supposed to be after line 59, for the @ command stuff. 

All the images after that are also in the wrong order!

2023-12-05 18:54 UTC, kalanchan commented on content/blogposts/2023/cody-vscode-0-18-release.md
> +  src="https://storage.googleapis.com/sourcegraph-assets/blog/blog-vscode-v018-release/blog-v018-editing-008.jpg"
could you turn this into a gif? I think it would be better for discoverability if the users knew how this popped up

2023-12-05 18:54 UTC, kalanchan commented on content/blogposts/2023/cody-vscode-0-18-release.md
> +  src="https://storage.googleapis.com/sourcegraph-assets/blog/blog-vscode-v018-release/cody-vscode-v0-18-010.png"
this is the same image as `https://storage.googleapis.com/sourcegraph-assets/blog/blog-vscode-v018-release/blog-v018-editing-008.jpg`

2023-12-05 18:54 UTC, kalanchan commented on content/blogposts/2023/cody-vscode-0-18-release.md
> +  src="https://storage.googleapis.com/sourcegraph-assets/blog/blog-vscode-v018-release/blog-v018-trigger-009.jpg"
yay this one is the in the right order

2023-12-05 20:39 UTC, kalanchan commented on content/blogposts/2023/cody-vscode-0-18-release.md
> +  caption="Context Controls"
```suggestion
  caption="Enhanced Context Control"
```

2023-12-05 20:40 UTC, kalanchan commented on content/blogposts/2023/cody-vscode-0-18-release.md
> +  caption="@-included files"
```suggestion
  caption="@-included files now supports fuzzy filename search"
```

2023-12-05 20:51 UTC, taylorsperry reviewed
LGTM! Will the New Search UI also be enabled by default (instead of behind a feature flag) with this release? I think we should (more feedback = more better), and include a very brief description of it. I don't see why we can't use what I added to the Cody GA: Release Blog: 

> We discovered that lots of users were using Cody chat to search for code snippets in their codebase but not getting the results they expected. We’ve added a new natural language search feature that uses a local index of your open project to surface code snippets that approximately match a description.

2023-12-05 20:54 UTC, kalanchan commented
@taylorsperry yes it is! check https://github.com/sourcegraph/cody/pull/2079 for reference. 

@jdorfman could you include taylor's blurb and another image of the search panel :)

2023-12-05 21:24 UTC, jdorfman commented
@kalanchan sure thing added it to the doc before I port it

2023-12-06 07:25 UTC, kalanchan approved these changes
ready to ship gogogo!

2023-12-06 18:36 UTC, merged